### ISSUE TITLE
Create a Dockerfile

### ISSUE THREAD

**Issue by kwolfe** [alexkazik/qnap-decrypt#1]
Hey! I tried to push some changes but don't have permission. I created a simple Dockerfile to use this in a container if you'd like to add it to the repo.

```
FROM ubuntu
ENV PATH="/root/.local/bin:${PATH}"
RUN apt-get update \
&& apt-get -y install --no-install-recommends ca-certificates git wget \
&& wget -qO- https://get.haskellstack.org/ | sh \
&& git clone https://github.com/alexkazik/qnap-decrypt.git \
&& cd qnap-decrypt \
&& stack install
```

**Comment by alexkazik** [comment]
Hi,

I’m not a fan of Docker but that shouldn’t be a reason to add it anyway.

Why do you clone the repo and don’t use `stack install qnap-decrypt --resolver …` instead (i.e. use the released package)?

Can you add an comment that you created it and add a way to contact you in case others need it?

(And optionally create a PR for it.)

**Comment by kwolfe** [comment]
I was just following your steps in the `README.md` file (I am not familiar with haskellstack). 

I'll make the following changes to the Dockerfile:
- remove the installation of the `git` package
- remove cloning `https://github.com/alexkazik/qnap-decrypt.git`
- remove `cd qnap-decrypt && stack install`
- add `stack install qnap-decrypt`

The use case for a Dockerfile was just a way to be able to install your awesome program in a container and use it when needed without the modification of the underlying OS. I'll fork the repository and create a PR.
