### ISSUE TITLE
"Unknown file type (the file is not encrypted or it's version is not known)"

### ISSUE THREAD

**Issue by cepm-nate** [alexkazik/qnap-decrypt#3]
I backed up a boatload of files using HBS (onto google cloud storage), and I think I had "encrypt client side" turned on in HBS. I have downloaded this program and tried to run it on the files. All it says is "Unknown file type (the file is not encrypted or it's version is not known)".

Is there a way to force it to try various versions? I don't remember exactly what HBS version was in use when the QNAP NAS crashed.

Thankfully I had an alternate backup for the important data, but I'd like to be able to decrypt this data (about 70 GB of vacation photos) without grabbing another NAS to put the drives into.

In Windows explorer all the files and folders are visible with the right filenames and extensions, but trying to open any of them does not work, or they open showing random characters.

**Comment by alexkazik** [comment]
This software only supports the (back then) current V2 software.

If you look into your files and they start with `__QCS__` then it's V1 and this software can decode them: https://github.com/Mikiya83/hbs_decipher

**Comment by cepm-nate** [comment]
Yea, these files start with "Salted__". QNAP tech support now says HBS does not encrypt the files, just compresses them. Perhaps I was using other software on QNAP to backup to Google Cloud storage. Oh well, I have a friend who's getting a new 8-bay QNAP and is willing to try dropping our drives in first to see if we can recover data. :-)

Thanks for writing the software and releasing it to the public!

**Comment by alexkazik** [comment]
You're welcome - sorry I couldn't help.
